name: Generate contribution snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/snake.yml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: kalaabalb
          outputs: |
            dist/snake-dark.svg?color_snake=#a78bfa&color_dots=#070812,#1a1531,#382a66,#a78bfa,#d39a52
            dist/snake-light.svg?color_snake=#7c3aed&color_dots=#f5f0ff,#e4dcfb,#c4b5fd,#7c3aed,#d39a52

      - name: Publish output branch
        uses: crazy-max/ghaction-github-pages@v5
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
